"""Hand-written metadata per glyph id (Indonesian prose).

Membership (which file belongs to which glyph) lives in assignments.json;
this module only describes each glyph.  KEPUTUSAN lists the judgment calls
that end up in catalog/SUMMARY.md.
"""
from __future__ import annotations

KATEGORI = ["menu", "subtes", "mapel", "profesi_bidang", "lembaga", "orang", "logo", "lainnya"]


def g(nama, kategori, deskripsi, sinonim):
    return {"nama": nama, "kategori": kategori, "tipe": "glyph",
            "deskripsi_visual": deskripsi, "sinonim": sinonim}


def logo(nama, deskripsi, sinonim):
    return {"nama": nama, "kategori": "logo", "tipe": "logo",
            "deskripsi_visual": deskripsi, "sinonim": sinonim}


META = {
    # ------------------------------------------------------------------ menu
    "materi": g("Materi / Course", "menu",
                "gugusan enam heksagon 3D dengan dua warna selang-seling",
                ["materi", "course", "modul belajar", "bahan ajar", "kelas online", "pelajaran", "silabus",
                 "ringkasan materi", "materi SKD", "materi UTBK", "e-learning", "belajar mandiri",
                 "study material", "kisi-kisi materi"]),
    "tryout": g("Tryout", "menu",
                "tumpukan kertas ujian bertanda A+ dengan pita bintang di pojok",
                ["tryout", "try out", "TO", "simulasi ujian", "ujian online", "mock test", "CAT",
                 "tryout SKD", "tryout UTBK", "ujian percobaan", "ranking nasional", "exam", "test",
                 "tryout akbar"]),
    "latsol": g("Latihan Soal (Latsol)", "menu",
                "papan presentasi di atas penyangga berisi daftar poin dan sosok perempuan",
                ["latihan soal", "latsol", "soal latihan", "quiz", "kuis", "practice", "exercise",
                 "drill soal", "bank soal", "pembahasan soal", "soal per bab", "uji pemahaman",
                 "latihan harian"]),
    "rapor": g("Rapor / Hasil Belajar", "menu",
               "dua lembar dokumen dengan huruf A dalam lingkaran dan garis-garis teks",
               ["rapor", "rapot", "report", "nilai", "skor", "hasil tryout", "hasil belajar",
                "statistik nilai", "evaluasi", "progres belajar", "transkrip", "score", "peringkat",
                "passing grade"]),
    "lapor_masalah": g("Lapor Masalah", "menu",
                       "balon chat berisi tiga titik dengan tanda tanya dalam lingkaran di pojok",
                       ["lapor masalah", "laporkan masalah", "bantuan", "help", "pengaduan", "keluhan",
                        "customer service", "support", "FAQ", "kendala teknis", "report bug",
                        "tanya admin", "hubungi kami"]),
    "pdf": g("PDF / Dokumen", "menu",
             "berkas dokumen dengan sudut terlipat dan label PDF besar",
             ["pdf", "e-book", "ebook", "modul pdf", "dokumen", "unduh", "download", "file materi",
              "rangkuman", "kisi-kisi", "bank soal pdf", "handout", "pdf gratis"]),
    "promo": g("Promo / Diskon", "menu",
               "lencana bergerigi dengan simbol persen dan tanda bintang kecil",
               ["promo", "diskon", "discount", "voucher", "kupon", "potongan harga", "sale",
                "penawaran spesial", "harga hemat", "cashback", "flash sale", "kode promo", "paket murah"]),
    "kalender": g("Kalender / Jadwal", "menu",
                  "kalender meja bertuliskan JAN dengan gambar pemandangan dan kisi tanggal",
                  ["kalender", "jadwal", "schedule", "agenda", "tanggal penting", "jadwal tryout",
                   "jadwal seleksi", "timeline", "pengingat", "reminder", "jadwal kelas", "event",
                   "calendar", "jadwal CPNS"]),
    "live_class": g("Live Class / Kelas Langsung", "menu",
                    "titik pusat dengan gelombang siaran melengkung di kiri dan kanan",
                    ["live class", "kelas live", "siaran langsung", "webinar", "zoom", "streaming",
                     "kelas online", "live teaching", "bimbel online", "kelas interaktif", "broadcast",
                     "tatap muka virtual", "live"]),
    "grup": g("Grup / Komunitas", "menu",
              "tiga orang berjas dan berdasi, satu di depan dan dua di belakang",
              ["grup", "group", "komunitas", "grup belajar", "grup telegram", "grup whatsapp",
               "forum diskusi", "tim", "jejaring kerja", "networking", "kerja sama tim", "teamwork",
               "anggota", "manajemen tim"]),
    "journey": g("Journey / Dibimbing", "menu",
                 "penanda lokasi (pin) berisi kubus di atas alas peta",
                 ["journey", "perjalanan belajar", "roadmap", "alur belajar", "dibimbing", "bimbingan",
                  "mentoring", "learning path", "peta belajar", "study plan", "langkah belajar",
                  "target belajar", "progres"]),
    "info": g("Info / Pengumuman", "menu",
              "pengeras suara dengan gelombang suara",
              ["info", "informasi", "pengumuman", "berita", "announcement", "update terbaru",
               "kabar seleksi", "notifikasi", "speaker", "news", "info CPNS", "info kedinasan",
               "broadcast"]),
    "tips": g("Tips / Diskusi", "menu",
              "dua balon percakapan bertumpuk, masing-masing berisi tiga titik",
              ["tips", "trik", "tips dan trik", "saran", "diskusi", "percakapan", "chat", "komunikasi",
               "bahasa dan komunikasi", "silogisme", "verbal", "obrolan", "strategi mengerjakan",
               "konsultasi"]),
    "link": g("Link / Tautan", "menu",
              "dua mata rantai yang saling terkait",
              ["link", "tautan", "url", "gabungan bagian", "penghubung", "koneksi", "rantai",
               "integrasi", "link pendaftaran", "sambungan", "hyperlink", "link penting"]),
    "drilling_soal": g("Drilling Soal", "menu",
                       "tumpukan lembar dokumen menyebar seperti kipas dengan garis teks",
                       ["drilling soal", "drill", "latihan intensif", "paket soal", "bank soal",
                        "kumpulan soal", "latihan berulang", "soal harian", "pendalaman soal",
                        "intensive practice", "soal HOTS", "latihan maraton"]),
    "kertas_soal": g("Kertas Soal / Lembar Ujian", "menu",
                     "lembar kertas penuh coretan tulisan dengan pena bulu (quill)",
                     ["kertas soal", "lembar soal", "lembar ujian", "ujian tulis", "tes tertulis",
                      "uji kemampuan", "TO gratis", "latihan soal tes", "written test", "exam paper",
                      "pedagogik", "structure and written expression", "soal esai"]),
    "tutup": g("Tutup / Close", "menu",
               "tanda silang X tiga dimensi",
               ["tutup", "close", "keluar", "batal", "cancel", "silang", "exit", "hapus", "tolak",
                "salah", "x"]),
    "layar_video": g("Video / Layar Putar", "menu",
                     "layar monitor dengan tombol play segitiga",
                     ["video", "video pembelajaran", "play", "putar video", "tonton", "rekaman kelas",
                      "video materi", "replay", "youtube", "pembahasan video", "VOD", "streaming"]),
    "buku_video": g("E-book / Buku Video", "menu",
                    "buku terbuka dengan kotak tombol play di halaman kiri",
                    ["e-book", "ebook", "buku digital", "buku video", "materi video", "modul interaktif",
                     "video pembelajaran", "perpustakaan digital", "e-modul", "buku online", "blanko",
                     "learning video"]),
    "monitor": g("Monitor / Belajar Online", "menu",
                 "monitor komputer menampilkan daftar poin dan kursor panah",
                 ["monitor", "komputer", "belajar online", "CAT", "computer assisted test",
                  "ujian berbasis komputer", "pengenalan", "orientasi", "direktori formasi",
                  "progres belajar", "tes pusat", "manajerial", "e-learning", "dashboard"]),
    "buku_pensil": g("Buku & Pensil", "menu",
                     "buku terbuka bergaris dengan pensil di halaman kanan",
                     ["buku pensil", "latihan soal", "latsol", "menulis", "mencatat", "catatan",
                      "sekolah rakyat", "latsol PPPK", "tugas", "pekerjaan rumah", "esai", "belajar"]),
    "lencana_tingkat_1": g("Lencana Tingkat 1 / Starter Test", "menu",
                           "lencana heksagon berbintang dengan satu chevron dan garis warna di bawah",
                           ["starter test", "tes awal", "level 1", "tingkat pemula", "lencana", "badge",
                            "placement test", "pretest", "beginner", "TOEFL starter", "pangkat", "rank 1"]),
    "lencana_tingkat_2": g("Lencana Tingkat 2 / Booster Test", "menu",
                           "lencana heksagon berbintang dengan dua chevron bersayap",
                           ["booster test", "level 2", "tingkat menengah", "lencana", "badge",
                            "intermediate", "TOEFL booster", "tes lanjutan", "naik level", "pangkat",
                            "rank 2", "latihan penguatan"]),
    "lencana_tingkat_3": g("Lencana Tingkat 3 / Ace Test", "menu",
                           "lencana heksagon berbintang dengan tiga chevron bersayap",
                           ["ace test", "level 3", "tingkat mahir", "lencana", "badge", "advanced",
                            "TOEFL ace", "tes akhir", "juara", "pangkat", "rank 3", "master"]),
    # ---------------------------------------------------------------- subtes
    "numerik": g("Numerik / Deret Angka", "subtes",
                 "empat ubin 2x2 berisi angka 3, 5, 7 dan tiga titik",
                 ["numerik", "deret angka", "angka hilang", "matematika", "TIU numerik",
                  "kemampuan numerik", "pola bilangan", "barisan bilangan", "number series",
                  "numerical reasoning", "logika angka", "berhitung", "TPA numerik",
                  "penalaran matematika"]),
    "kalkulator": g("Kalkulator / Numerik Berhitung", "subtes",
                    "empat ubin 2x2 berisi simbol kurang, tambah, bagi dan kali",
                    ["kalkulator", "berhitung", "aritmetika", "operasi hitung", "numerik berhitung",
                     "calculation test", "kecerdasan", "TKD", "tambah kurang kali bagi",
                     "matematika dasar", "hitung cepat", "arithmetic", "TIU hitungan"]),
    "soal_cerita": g("Soal Cerita / Verbal (ubin abc)", "subtes",
                     "empat ubin 2x2 berisi abc, angka 5, cba dan titik-titik",
                     ["soal cerita", "verbal", "huruf hilang", "logic reasoning", "grammar",
                      "numerik soal cerita", "penalaran logis", "literasi numerasi", "word problem",
                      "pola huruf", "TIU verbal", "substantif numerik", "kemampuan bahasa"]),
    "kuantitatif": g("Kuantitatif / Perbandingan Kuantitatif", "subtes",
                     "empat ubin 2x2 berisi (x), (y), tanda >= dan tiga titik",
                     ["kuantitatif", "perbandingan kuantitatif", "penalaran kuantitatif", "PK",
                      "pengetahuan kuantitatif", "aljabar", "variabel x y", "pertidaksamaan", "hitungan",
                      "TPA kuantitatif", "quantitative reasoning", "UTBK PK", "TIU", "matematika"]),
    "figural_serial": g("Figural Serial / Pola Gambar", "subtes",
                        "empat ubin 2x2 berisi lingkaran bertangkai yang berputar dan tiga titik",
                        ["figural", "figural serial", "pola gambar", "simbol hilang", "deret gambar",
                         "penalaran induktif", "gambar berurutan", "TIU figural", "abstract reasoning",
                         "rotasi gambar", "visual pattern", "psikotes gambar", "tes penalaran"]),
    "figural_ketidaksamaan": g("Figural Ketidaksamaan", "subtes",
                               "empat ubin 2x2 berisi lingkaran bergaris miring (dicoret) dan tiga titik",
                               ["figural ketidaksamaan", "gambar yang berbeda", "odd one out",
                                "ketidaksamaan", "error recognition", "mencari perbedaan", "figural",
                                "TIU figural", "penalaran gambar", "abstract reasoning",
                                "kecermatan visual", "psikotes"]),
    "figural_analogi": g("Figural Analogi", "subtes",
                         "empat ubin 2x2 berisi bentuk jam pasir/X, garis sejajar dan tiga titik",
                         ["figural analogi", "analogi gambar", "hubungan gambar", "pola analogi",
                          "TIU figural", "penalaran analitis", "PPU", "pengetahuan dan pemahaman umum",
                          "kraepelin", "pauli", "abstract reasoning", "visual analogy", "psikotes"]),
    "puzzle": g("Puzzle / SKD", "subtes",
                "tiga keping puzzle 3D yang saling mengunci",
                ["puzzle", "SKD", "seleksi kompetensi dasar", "tryout SKD", "TWK TIU TKP",
                 "tes kompetensi", "tryout tahap 2", "tryout PPPK", "pemecahan masalah",
                 "problem solving", "kepingan", "strategi", "logika"]),
    "puzzle_matematika": g("Puzzle Matematika", "subtes",
                           "tiga keping puzzle dengan simbol minus dan kali",
                           ["puzzle matematika", "matematika", "numerik", "kemampuan umum numerik",
                            "materi matematika", "operasi hitung", "TKU numerik", "soal matematika",
                            "berhitung", "logika matematika", "aritmetika"]),
    "puzzle_listrik": g("Puzzle Listrik / TKP PLN", "subtes",
                        "tiga keping puzzle dengan simbol petir dan steker",
                        ["puzzle listrik", "TKP PLN", "PLN", "kelistrikan", "energi",
                         "tes karakteristik pribadi", "rekrutmen PLN", "steker", "petir", "BUMN energi",
                         "listrik"]),
    "topeng_drama": g("Topeng Drama / TKP", "subtes",
                      "dua topeng teater, satu tersenyum dan satu sedih",
                      ["TKP", "tes karakteristik pribadi", "kepribadian", "tes kepribadian",
                       "psikologi kepribadian", "akhlak", "profesionalisme", "karakter", "sikap kerja",
                       "integritas", "personality test", "topeng", "emosi", "SKD"]),
    "garuda": g("Garuda / TWK", "subtes",
                "kepala burung garuda menghadap kiri dengan bulu leher bergerigi",
                ["garuda", "TWK", "tes wawasan kebangsaan", "nasionalisme", "kebangsaan", "pancasila",
                 "PKn", "PPKn", "bela negara", "NKRI", "wawasan kebangsaan", "UUD 1945", "pilar negara",
                 "ideologi"]),
    "tengkorak_lup": g("Tengkorak & Lup / Psikologi", "subtes",
                       "tengkorak dengan kaca pembesar menutupi satu mata",
                       ["psikologi", "kepribadian", "psikotes", "mental ideologi", "SJT",
                        "situational judgement test", "antropologi", "analisis karakter",
                        "tes psikologi", "kejiwaan", "profiling", "investigasi", "psikologi tamtama"]),
    "buku_psi": g("Buku Psikologi (Ψ) / Psikotes", "subtes",
                  "buku tebal bersampul simbol psi (Ψ)",
                  ["psikotes", "psikologi", "tes psikologi", "psikometri", "penarikan kesimpulan",
                   "tes IQ", "tes bakat", "psychology", "psi", "tes kecerdasan", "logika", "penalaran",
                   "buku psikologi"]),
    "verbal": g("Verbal / Balon Bicara", "subtes",
                "balon bicara besar berisi tiga titik dengan gelombang sinyal di pojok",
                ["verbal", "kemampuan verbal", "kemampuan umum verbal", "sinonim antonim",
                 "analogi kata", "TIU verbal", "penalaran verbal", "verbal reasoning", "kosakata",
                 "bahasa", "komunikasi", "berbicara", "TPA verbal"]),
    "kubus_bertumpuk": g("Kubus Bertumpuk / Penalaran Ruang", "subtes",
                         "piramida kubus isometrik tersusun tiga tingkat",
                         ["kubus", "kubus bertumpuk", "penalaran ruang", "tata ruang", "menentukan bentuk",
                          "spasial", "9 kotak", "agility", "hitung kubus", "bangun ruang",
                          "spatial reasoning", "kompetensi bidang", "penalaran"]),
    "abstraksi_ruang": g("Abstraksi Ruang / Integritas", "subtes",
                         "panel persegi 3D bertumpuk miring dengan siku bingkai di pojok",
                         ["abstraksi ruang", "integritas", "spasial", "perspektif", "bingkai",
                          "bentuk ruang", "visual spasial", "penalaran ruang", "TWK", "kejujuran",
                          "spatial", "bidang"]),
    "rbb_d3_s2": g("RBB D3–S2", "subtes",
                   "panel abstraksi ruang dengan tulisan D3-S2 di bagian atas",
                   ["RBB", "rekrutmen bersama BUMN", "D3-S2", "fresh graduate", "lulusan diploma",
                    "sarjana", "magister", "BUMN", "RBB D3 S2", "lowongan BUMN", "tes BUMN", "FHCI"]),
    "rbb_sma": g("RBB SMA", "subtes",
                 "panel abstraksi ruang dengan tulisan SMA di bagian atas",
                 ["RBB", "rekrutmen bersama BUMN", "SMA", "SMK", "lulusan SMA", "BUMN", "RBB SMA",
                  "lowongan BUMN", "tes BUMN", "FHCI", "sederajat", "jalur SMA"]),
    "perisai": g("Perisai / SKB & Bela Negara", "subtes",
                 "perisai dua warna dengan kubus 3D di tengah",
                 ["perisai", "SKB", "seleksi kompetensi bidang", "SKB CPNS", "bela negara", "pertahanan",
                  "keamanan", "proteksi", "makroprudensial", "kompetensi bidang", "shield",
                  "ketahanan nasional", "TWK"]),
    "akhlak_a": g("AKHLAK – A (Amanah / Adaptif)", "subtes",
                  "huruf A 3D dengan tulisan 'akhlak' vertikal di sisi kiri",
                  ["akhlak", "AKHLAK A", "amanah", "adaptif", "core values BUMN", "nilai AKHLAK",
                   "tes AKHLAK", "rekrutmen bersama BUMN", "budaya kerja", "integritas", "huruf A",
                   "values"]),
    "akhlak_h": g("AKHLAK – H (Harmonis)", "subtes",
                  "huruf H 3D dengan tulisan 'akhlak' vertikal di sisi kiri",
                  ["akhlak", "AKHLAK H", "harmonis", "core values BUMN", "nilai AKHLAK", "tes AKHLAK",
                   "rekrutmen bersama BUMN", "budaya kerja", "saling peduli", "menghargai perbedaan",
                   "huruf H", "values"]),
    "akhlak_k": g("AKHLAK – K (Kompeten / Kolaboratif)", "subtes",
                  "huruf K 3D dengan tulisan 'akhlak' vertikal di sisi kiri",
                  ["akhlak", "AKHLAK K", "kompeten", "kolaboratif", "core values BUMN", "nilai AKHLAK",
                   "tes AKHLAK", "rekrutmen bersama BUMN", "budaya kerja", "kerja sama", "huruf K",
                   "values"]),
    "akhlak_l": g("AKHLAK – L (Loyal)", "subtes",
                  "huruf L 3D dengan tulisan 'akhlak' vertikal di sisi kiri",
                  ["akhlak", "AKHLAK L", "loyal", "loyalitas", "core values BUMN", "nilai AKHLAK",
                   "tes AKHLAK", "rekrutmen bersama BUMN", "budaya kerja", "dedikasi", "huruf L",
                   "values"]),
    "diagram_pai": g("Diagram Lingkaran / TPA", "subtes",
                     "diagram pai 3D terpotong empat dengan angka 10, 20, 50, 70",
                     ["TPA", "tes potensi akademik", "diagram lingkaran", "pie chart", "statistik",
                      "data", "grafik", "analisis data", "persentase", "interpretasi data", "chart",
                      "TPA BUMN", "TPA OJK"]),
    "sempoa": g("Sempoa / Aritmetika", "subtes",
                "sempoa (abakus) dengan dua manik pada batang",
                ["sempoa", "abakus", "aritmetika", "arithmetic", "berhitung", "hitung cepat", "numerik",
                 "matematika dasar", "kalkulasi", "operasi hitung", "kecepatan hitung", "tes aritmetika"]),
    "mata_coret": g("Mata Dicoret / Tes Buta Warna", "subtes",
                    "ikon mata dengan garis coret diagonal",
                    ["buta warna", "tes buta warna", "ishihara", "mata", "penglihatan",
                     "tes kesehatan mata", "color blind", "blind test", "persepsi warna", "tes kesehatan",
                     "visual", "rikkes"]),
    "buku_lup": g("Buku & Lup / Kecermatan", "subtes",
                  "buku terbuka dengan kaca pembesar di atas halaman",
                  ["kecermatan", "ketelitian", "tes kecermatan", "teliti", "fokus", "konsentrasi",
                   "membaca cermat", "pencarian", "detail", "psikotes kecermatan", "accuracy",
                   "tes ketelitian"]),
    "bulu": g("Dua Bulu / Sosial Budaya", "subtes",
              "dua helai bulu burung bersilangan (besar dan kecil)",
              ["bulu", "pena bulu", "sosial budaya", "TKP", "seni rupa", "tes psikiatri", "bedah soal",
               "latsol PPPK", "tes SKB", "toefl tryout", "kreativitas", "budaya", "feather"]),
    "buku_terbuka": g("Buku Terbuka / Reading & Literasi", "subtes",
                      "buku terbuka dengan baris-baris teks tebal di kedua halaman",
                      ["reading", "membaca", "literasi", "buku", "verbal", "pemahaman bacaan",
                       "reading comprehension", "bacaan", "teks bacaan", "literasi membaca",
                       "TOEFL reading", "substantif literasi", "perpustakaan"]),
    "headphone": g("Headphone / Listening", "subtes",
                   "headphone dengan gelombang suara dan tombol play",
                   ["listening", "listening comprehension", "headphone", "audio", "mendengarkan",
                    "TOEFL listening", "IELTS listening", "rekaman suara", "english listening", "simak",
                    "earphone", "podcast"]),
    "push_up": g("Push Up / Tes Jasmani", "subtes",
                 "pria berkaus hijau sedang push up dengan pegangan",
                 ["jasmani", "tes jasmani", "push up", "kesamaptaan", "samapta", "kebugaran", "olahraga",
                  "latihan fisik", "tes fisik", "TNI polri", "fitness", "garjas"]),
    "hati_tangan": g("Hati di Tangan / Kesehatan Jiwa", "subtes",
                     "hati bertanda plus di atas telapak tangan",
                     ["kesehatan jiwa", "kesehatan mental", "mental health", "tes kesehatan jiwa", "MMPI",
                      "psikiatri", "kepedulian", "empati", "peduli", "kasih sayang", "rikkes jiwa",
                      "wellbeing"]),
    "tangan_ikrar": g("Tangan Ikrar / Anti Radikalisme", "subtes",
                      "tangan mengacungkan tiga jari di dalam lingkaran",
                      ["anti radikalisme", "TKP", "ikrar", "sumpah", "janji setia", "deradikalisasi",
                       "toleransi", "nasionalisme", "integritas", "tangan", "pledge", "moderasi"]),
    "bendera_indonesia": g("Bendera Indonesia / Bahasa Negara", "subtes",
                           "bendera merah putih dalam cincin berbentuk balon bicara",
                           ["bendera indonesia", "merah putih", "bahasa negara", "TWK", "nasionalisme",
                            "kebangsaan", "NKRI", "simbol negara", "bahasa indonesia", "lambang negara",
                            "indonesia", "patriotisme"]),
    # ----------------------------------------------------------------- mapel
    "atom": g("Atom / Fisika", "mapel",
              "model atom dengan inti dan tiga orbit elektron",
              ["fisika", "atom", "sains", "saintek", "IPA", "physics", "mekanika", "listrik magnet",
               "UTBK saintek", "olimpiade fisika", "ilmu pengetahuan alam", "eksakta", "TKA fisika"]),
    "dna": g("DNA / Biologi", "mapel",
             "untai heliks ganda DNA",
             ["biologi", "DNA", "genetika", "sains", "saintek", "IPA", "biology", "sel", "makhluk hidup",
              "jasmani", "anatomi", "bioteknologi", "TKA biologi"]),
    "mikroskop": g("Mikroskop & Labu / Kimia", "mapel",
                   "mikroskop dan labu erlenmeyer berisi cairan",
                   ["kimia", "mikroskop", "laboratorium", "eksperimen", "sains", "saintek", "IPA",
                    "chemistry", "penelitian", "tabung reaksi", "skolastik", "riset", "TKA kimia"]),
    "globe": g("Globe / Geografi & Pengetahuan Umum", "mapel",
               "bola dunia di atas penyangga melengkung",
               ["globe", "geografi", "peta dunia", "pengetahuan umum", "wawasan global", "bumi",
                "penalaran umum", "tes kemampuan umum", "TIU", "soshum", "IPS", "general knowledge",
                "IPA terpadu"]),
    "uang": g("Uang / Ekonomi", "mapel",
              "tumpukan uang kertas bertanda Rp",
              ["uang", "ekonomi", "keuangan", "rupiah", "sektor jasa keuangan", "akuntansi", "koperasi",
               "perbankan", "finance", "money", "soshum", "investasi", "OJK", "manajemen keuangan"]),
    "museum": g("Museum / Sejarah", "mapel",
                "gedung klasik berpilar dengan gulungan naskah di tengah",
                ["sejarah", "museum", "gedung bersejarah", "naskah kuno", "arsip", "soshum", "IPS",
                 "history", "peradaban", "cagar budaya", "prasasti", "sejarah indonesia"]),
    "keluarga": g("Keluarga / Sosiologi", "mapel",
                  "keluarga: ayah, ibu dan anak",
                  ["keluarga", "sosiologi", "masyarakat", "sosial", "sosiokultural", "soshum", "IPS",
                   "hubungan sosial", "family", "orang tua dan anak", "pelayanan sosial", "kependudukan",
                   "grup"]),
    "bahasa_inggris": g("Bahasa Inggris (balon EN)", "mapel",
                        "dua balon percakapan bertumpuk bertuliskan EN",
                        ["bahasa inggris", "english", "EN", "TOEFL", "TBI", "tes bahasa inggris",
                         "structure", "grammar", "IELTS", "speaking", "conversation", "english test",
                         "percakapan"]),
    "bahasa_indonesia": g("Bahasa Indonesia (balon INA)", "mapel",
                          "dua balon percakapan bertumpuk bertuliskan INA",
                          ["bahasa indonesia", "INA", "bahasa", "PUEBI", "EYD", "tata bahasa", "wawancara",
                           "percakapan", "komunikasi", "literasi bahasa", "UKBI", "bahasa baku",
                           "tes bahasa"]),
    "bendera_inggris": g("Bendera Inggris", "mapel",
                         "bendera Union Jack dalam cincin berbentuk balon bicara",
                         ["bendera inggris", "union jack", "bahasa inggris", "english", "TOEFL",
                          "written expression", "british", "UK", "tes toefl", "IELTS", "english course",
                          "listening"]),
    "bendera_arab": g("Bendera Arab Saudi / Bahasa Arab", "mapel",
                      "bendera Arab Saudi dalam cincin berbentuk balon bicara",
                      ["bahasa arab", "bendera arab", "arab saudi", "arabic", "pendidikan bahasa arab",
                       "PBA", "madrasah", "kemenag", "timur tengah", "huruf hijaiyah", "nahwu",
                       "PPG bahasa arab"]),
    "quran_rehal": g("Kitab di Rehal / Pendidikan Agama Islam", "mapel",
                     "kitab terbuka di atas rehal dengan bulan sabit",
                     ["pendidikan agama islam", "PAI", "al quran", "rehal", "kitab suci", "mengaji",
                      "agama islam", "madrasah", "tahfidz", "kemenag", "religi", "PPG PAI"]),
    "alkitab_salib": g("Alkitab & Salib / Pendidikan Agama Kristen", "mapel",
                       "kitab terbuka dengan salib bercahaya di atasnya",
                       ["pendidikan agama kristen", "PAK", "alkitab", "salib", "kitab suci", "kristen",
                        "gereja", "agama", "religi", "teologi", "rohani", "PPG agama kristen"]),
    "guru_olahraga": g("Guru Olahraga / PJOK", "mapel",
                       "pria bertopi dengan peluit di leher",
                       ["PJOK", "olahraga", "pendidikan jasmani", "guru olahraga", "pelatih", "coach",
                        "peluit", "kebugaran", "penjas", "sport", "kesehatan", "PPG PJOK"]),
    # -------------------------------------------------------- profesi_bidang
    "tas_medis": g("Tas Medis / Kesehatan", "profesi_bidang",
                   "tas medis bertanda palang dengan dua tali",
                   ["kesehatan", "medis", "tes kesehatan", "P3K", "dokter", "poltekkes", "perawat",
                    "tenaga kesehatan", "nakes", "rumah sakit", "medical check up", "health", "rikkes",
                    "kesehatan dan medis"]),
    "koper": g("Koper Kerja / Karier", "profesi_bidang",
               "tas kerja (koper) dengan pegangan dan gesper",
               ["koper", "tas kerja", "lowongan kerja", "loker", "karier", "pekerjaan", "pendaftaran",
                "administrasi", "perkantoran", "wirausaha", "bisnis", "job", "rekrutmen", "formasi"]),
    "palu_hakim": g("Palu Hakim / Hukum", "profesi_bidang",
                    "palu hakim mengetuk alas dengan percikan",
                    ["hukum", "palu hakim", "peradilan", "kebijakan", "regulasi", "undang-undang", "legal",
                     "soshum", "pengadilan", "keadilan", "peraturan OJK", "hakim", "hukum dan kebijakan"]),
    "satelit": g("Parabola / Teknologi & Komunikasi", "profesi_bidang",
                 "antena parabola memancarkan sinyal dengan perangkat di bawahnya",
                 ["satelit", "parabola", "teknologi informasi", "TIK", "telekomunikasi", "komunikasi",
                  "sinyal", "jaringan", "saintek", "IT", "antena", "digital", "teknologi dan komunikasi"]),
    "tanda_listrik": g("Tanda Listrik / Elektronika", "profesi_bidang",
                       "rambu segitiga peringatan dengan petir",
                       ["listrik", "tegangan tinggi", "petir", "teknik elektronika", "elektro",
                        "kelistrikan", "PLN", "bahaya listrik", "energi", "rambu peringatan",
                        "teknik listrik", "arus listrik"]),
    "menara_listrik": g("Menara Transmisi / Jaringan & Telekomunikasi", "profesi_bidang",
                        "tiga menara transmisi dengan kabel",
                        ["menara transmisi", "tower", "sutet", "jaringan", "telekomunikasi",
                         "teknik jaringan komputer", "TKJ", "kabel", "infrastruktur", "BTS", "listrik",
                         "sinyal"]),
    "piston_mesin": g("Piston & Gir / Teknik Mesin", "profesi_bidang",
                      "dua piston bersilang di atas roda gigi",
                      ["teknik mesin", "mesin", "piston", "roda gigi", "otomotif", "mekanik", "manufaktur",
                       "bengkel", "engine", "SMK teknik", "permesinan", "mechanical engineering"]),
    "mobil_bengkel": g("Mobil & Kunci / Teknik Otomotif", "profesi_bidang",
                       "mobil dengan roda gigi dan kunci pas",
                       ["otomotif", "teknik otomotif", "mobil", "bengkel", "kunci pas", "servis kendaraan",
                        "mekanik", "kendaraan", "TKR", "SMK otomotif", "perbaikan", "automotive"]),
    "tukang_las": g("Tukang Las / Pengelasan", "profesi_bidang",
                    "pekerja berhelm las dan rompi memegang obor las",
                    ["pengelasan", "las", "welder", "fabrikasi logam", "teknik pengelasan", "bengkel las",
                     "K3", "logam", "konstruksi", "SMK teknik", "industri", "welding"]),
    "koki": g("Koki / Kuliner", "profesi_bidang",
              "koki bertopi chef dan berseragam",
              ["kuliner", "koki", "chef", "tata boga", "memasak", "masakan", "restoran", "perhotelan",
               "SMK tata boga", "food", "dapur", "pastry"]),
    "monitor_desain": g("Monitor Desain / DKV", "profesi_bidang",
                        "monitor menampilkan ilustrasi gunung dan panel desain dengan pena",
                        ["desain komunikasi visual", "DKV", "desain grafis", "ilustrasi", "multimedia",
                         "kreatif", "seni digital", "graphic design", "editing", "UI/UX", "layout",
                         "pen tablet"]),
    "monitor_jaringan": g("Monitor Diagram / Informatika", "profesi_bidang",
                          "monitor menampilkan diagram simpul yang saling terhubung",
                          ["informatika", "komputer", "jaringan", "algoritma", "diagram alir", "data", "IT",
                           "teknologi informasi", "pemrograman", "sistem informasi", "ilmu komputer",
                           "TIK"]),
    "monitor_kode": g("Monitor Kode / Rekayasa Perangkat Lunak", "profesi_bidang",
                      "monitor menampilkan simbol </> dan baris kode berwarna",
                      ["pemrograman", "coding", "kode", "perangkat lunak", "software", "game", "RPL",
                       "developer", "programmer", "web", "aplikasi", "informatika"]),
    "mikrofon_video": g("Mikrofon & Video / Broadcasting", "profesi_bidang",
                        "mikrofon studio dan balon berisi pemutar video",
                        ["broadcasting", "perfilman", "mikrofon", "video", "siaran", "penyiar", "podcast",
                         "jurnalistik", "multimedia", "film", "rekaman", "media"]),
    "produk_pangan": g("Produk Pangan / Agroteknologi & Gizi", "profesi_bidang",
                       "botol dan toples berlabel tunas tanaman dengan tanda centang",
                       ["agroteknologi", "pengolahan hasil pertanian", "pangan", "gizi",
                        "badan gizi nasional", "BGN", "makanan sehat", "produk olahan", "pertanian",
                        "nutrisi", "keamanan pangan", "makan bergizi gratis"]),
    "perisai_gembok": g("Perisai Gembok / Keamanan", "profesi_bidang",
                        "perisai dengan gembok di tengah",
                        ["keamanan", "keselamatan", "gembok", "perisai gembok", "K3", "security",
                         "perlindungan", "privasi", "proteksi data", "keamanan siber", "safety",
                         "satpam"]),
    "roda_gigi": g("Roda Gigi / Teknik & Operasional", "profesi_bidang",
                   "roda gigi dengan kubus 3D di tengah",
                   ["roda gigi", "gear", "teknik operasional", "operasional", "manajerial", "checking test",
                    "psikometri", "mekanik", "sistem", "proses kerja", "engineering", "sandi negara",
                    "SSN"]),
    "bulan_bintang": g("Bulan Bintang / Keagamaan", "profesi_bidang",
                       "bintang segi delapan berisi bulan sabit dan bintang",
                       ["keagamaan", "agama islam", "bulan bintang", "UM-PTKIN", "PTKIN", "islami",
                        "pendidikan agama", "madrasah", "kemenag", "religi", "moderasi beragama",
                        "muslim"]),
    "pangkat_akmil": g("Pangkat Akmil", "profesi_bidang",
                       "lencana pangkat hijau berbentuk lengkung runcing",
                       ["akmil", "akademi militer", "perwira", "taruna", "TNI", "tentara", "lencana pangkat",
                        "prajurit", "seleksi akmil", "karier militer", "pangkat", "AAL AAU"]),
    "pangkat_bintara": g("Pangkat Bintara", "profesi_bidang",
                         "tiga chevron hijau bertumpuk",
                         ["bintara", "pangkat bintara", "chevron", "TNI", "prajurit", "seleksi bintara",
                          "sersan", "militer", "tentara", "pangkat", "karier militer", "bintara polri"]),
    "pangkat_tamtama": g("Pangkat Tamtama", "profesi_bidang",
                         "tiga balok hijau mendatar",
                         ["tamtama", "pangkat tamtama", "prajurit", "TNI", "militer", "tentara",
                          "seleksi tamtama", "balok pangkat", "pangkat", "kopral", "karier militer",
                          "prada"]),
    # --------------------------------------------------------------- lembaga
    "gedung_pilar": g("Gedung Pilar / Lembaga Negara", "lembaga",
                      "gedung klasik dengan atap segitiga dan empat pilar",
                      ["pilar negara", "lembaga negara", "kebanksentralan", "bank indonesia",
                       "pemerintahan", "institusi", "infrastruktur", "kementerian", "gedung", "konstitusi",
                       "empat pilar kebangsaan", "TWK", "pemerintah"]),
    "obat_tablet": g("Tablet Obat / Farmasi", "lembaga",
                     "dua tablet obat berbentuk cakram",
                     ["obat", "tablet", "farmasi", "apotek", "kimia farma", "BUMN farmasi", "kesehatan",
                      "pil", "industri farmasi", "apoteker", "obat-obatan", "BUMN kesehatan"]),
    # ----------------------------------------------------------------- orang
    "toga": g("Wisudawati / Toga", "orang",
              "perempuan berambut panjang memakai topi toga",
              ["toga", "wisuda", "pendidikan", "akademik", "sarjana", "lulusan", "tes potensi akademik",
               "TKA", "pelatihan dan penelitian", "kampus", "mahasiswa", "graduation", "beasiswa",
               "SKB kemenhub"]),
    "toga_pria": g("Wisudawan / Toga Pria", "orang",
                   "laki-laki berambut pendek memakai topi toga",
                   ["toga", "wisudawan", "wisuda", "lulusan", "pendidikan", "sekolah rakyat",
                    "pendidikan luar biasa", "akademik", "sarjana", "graduation", "guru", "mahasiswa"]),
    "headset_cs": g("Headset CS / Pelayanan", "orang",
                    "perempuan memakai headset dengan mikrofon",
                    ["customer service", "CS", "pelayanan publik", "wawancara", "headset", "call center",
                     "bimbingan konseling", "konsultasi", "layanan", "operator", "helpdesk",
                     "scoring guidance", "wawancara psikologi"]),
    "guru": g("Guru / Pendidik", "orang",
              "pria berjenggot berdasi di depan papan tulis hijau",
              ["guru", "pendidik", "PPG", "PPG dalam jabatan", "PPG prajabatan", "pengajar", "teacher",
               "dosen", "sertifikasi guru", "mengajar", "profesi guru", "kelas"]),
    "guru_sd": g("Guru SD / PGSD", "profesi_bidang",
                 "guru perempuan menunjuk papan tulis bertuliskan 1+1",
                 ["guru SD", "PGSD", "pendidikan guru sekolah dasar", "guru kelas", "mengajar",
                  "sekolah dasar", "pendidik", "berhitung", "teacher", "PPG PGSD", "calistung",
                  "wali kelas"]),
    "guru_paud": g("Guru PAUD / PG-PAUD", "profesi_bidang",
                   "guru perempuan menggandeng dua anak kecil",
                   ["guru PAUD", "PG-PAUD", "pendidikan anak usia dini", "TK", "taman kanak-kanak",
                    "anak-anak", "pengasuh", "pendidik", "bermain", "PPG PAUD", "early childhood",
                    "kelompok bermain"]),
    "kerumunan": g("Kerumunan / Masyarakat", "orang",
                   "sekelompok siluet orang berdiri berjajar",
                   ["masyarakat", "kerumunan", "penduduk", "sosial", "IPS", "guru IPS", "mental ideologi",
                    "publik", "warga", "komunitas", "massa", "demografi"]),
    # --------------------------------------------------------------- lainnya
    "kristal": g("Kristal", "lainnya",
                 "dua kristal runcing di atas batu dengan kilau bintang",
                 ["kristal", "batu mulia", "permata", "geofisika", "STMKG", "tryout tahap 1", "mineral",
                  "berlian", "prestasi", "keunggulan", "crystal", "geologi"]),
    # ------------------------------------------------------------------ logo
    "logo_gunadarma": logo("Universitas Gunadarma", "logo Universitas Gunadarma (obor dalam lingkaran ungu)",
                           ["Universitas Gunadarma", "UG", "Gundar", "Depok", "PTS"]),
    "logo_uad": logo("Universitas Ahmad Dahlan", "logo Universitas Ahmad Dahlan (matahari Muhammadiyah)",
                     ["Universitas Ahmad Dahlan", "UAD", "Yogyakarta", "PTS Muhammadiyah"]),
    "logo_binus": logo("Binus University", "logo BINUS University",
                       ["Binus University", "BINUS", "Bina Nusantara", "Jakarta", "PTS"]),
    "logo_ipb": logo("Institut Pertanian Bogor", "logo IPB (tunas daun dalam lingkaran biru)",
                     ["Institut Pertanian Bogor", "IPB", "IPB University", "Bogor", "PTN"]),
    "logo_itb": logo("Institut Teknologi Bandung", "logo ITB (Ganesha dalam lingkaran biru)",
                     ["Institut Teknologi Bandung", "ITB", "Bandung", "PTN"]),
    "logo_its": logo("Institut Teknologi Sepuluh Nopember", "logo ITS (tugu dan teratai dalam roda gigi)",
                     ["Institut Teknologi Sepuluh Nopember", "ITS", "Surabaya", "PTN"]),
    "logo_mercu_buana": logo("Universitas Mercu Buana", "logo Universitas Mercu Buana",
                             ["Universitas Mercu Buana", "UMB", "Mercu Buana", "Jakarta", "PTS"]),
    "logo_petra": logo("Universitas Kristen Petra", "logo Universitas Kristen Petra (salib dalam lingkaran)",
                       ["Universitas Kristen Petra", "UK Petra", "Petra Christian University", "Surabaya",
                        "PTS"]),
    "logo_telkom_university": logo("Telkom University",
                                   "logo Telkom University (huruf U abu-abu dan buku merah) bergaya 3D",
                                   ["Telkom University", "Tel-U", "Universitas Telkom", "Bandung", "PTS"]),
    "logo_trisakti": logo("Universitas Trisakti",
                          "logo Universitas Trisakti digambar ulang dengan warna brand (merah)",
                          ["Universitas Trisakti", "Usakti", "Trisakti", "Jakarta", "PTS"]),
    "logo_ugm": logo("Universitas Gadjah Mada", "logo UGM (lambang surya bunga krem-cokelat)",
                     ["Universitas Gadjah Mada", "UGM", "Yogyakarta", "PTN"]),
    "logo_ui": logo("Universitas Indonesia", "logo UI (makara kuning)",
                    ["Universitas Indonesia", "UI", "Depok", "PTN", "makara"]),
    "logo_umy": logo("Universitas Muhammadiyah Yogyakarta", "logo UMY (lambang hijau-kuning)",
                     ["Universitas Muhammadiyah Yogyakarta", "UMY", "Yogyakarta", "PTS Muhammadiyah"]),
    "logo_unj": logo("Universitas Negeri Jakarta", "logo UNJ (lambang hijau-kuning)",
                     ["Universitas Negeri Jakarta", "UNJ", "Jakarta", "PTN"]),
    "logo_uny": logo("Universitas Negeri Yogyakarta", "logo UNY (lambang ungu-kuning)",
                     ["Universitas Negeri Yogyakarta", "UNY", "Yogyakarta", "PTN"]),
    "logo_upi": logo("Universitas Pendidikan Indonesia", "logo UPI (merah-hitam-kuning)",
                     ["Universitas Pendidikan Indonesia", "UPI", "Bandung", "PTN"]),
    "logo_uns": logo("Universitas Sebelas Maret", "logo UNS (lingkaran biru bertuliskan UNS)",
                     ["Universitas Sebelas Maret", "UNS", "Surakarta", "Solo", "PTN"]),
    "logo_surabaya": logo("Lambang Kota Surabaya (file Icon-USU)",
                          "perisai biru dengan Tugu Pahlawan, ikan sura dan buaya (lambang Kota Surabaya)",
                          ["Lambang Kota Surabaya", "Surabaya", "Kota Pahlawan", "Tugu Pahlawan",
                           "Jawa Timur", "sura dan baya"]),
    "logo_udayana": logo("Universitas Udayana", "logo Universitas Udayana (lingkaran biru-kuning)",
                         ["Universitas Udayana", "Unud", "Denpasar", "Bali", "PTN"]),
    "logo_unair": logo("Universitas Airlangga", "logo Universitas Airlangga (Garuda Airlangga dalam lingkaran)",
                       ["Universitas Airlangga", "Unair", "Surabaya", "PTN"]),
    "logo_undip": logo("Universitas Diponegoro", "logo Universitas Diponegoro",
                       ["Universitas Diponegoro", "Undip", "Semarang", "PTN"]),
    "logo_unnes": logo("Universitas Negeri Semarang", "logo UNNES (lambang kuning dan tulisan UNNES)",
                       ["Universitas Negeri Semarang", "Unnes", "Semarang", "PTN"]),
    "logo_unpad": logo("Universitas Padjadjaran", "logo Unpad (perisai kuning dengan obor)",
                       ["Universitas Padjadjaran", "Unpad", "Bandung", "Jatinangor", "PTN"]),
    "logo_unpas": logo("Universitas Pasundan", "logo Universitas Pasundan (perisai kuning)",
                       ["Universitas Pasundan", "Unpas", "Bandung", "PTS"]),
    "logo_untar": logo("Universitas Tarumanagara", "logo Universitas Tarumanagara (garis merah)",
                       ["Universitas Tarumanagara", "Untar", "Jakarta", "PTS"]),
    "logo_smm_ptn_barat": logo("SMM PTN-Barat", "logo SMM PTN-Barat / BKS PTN Barat (bunga dalam lingkaran)",
                               ["SMM PTN-Barat", "Seleksi Masuk Mandiri PTN Barat", "BKS PTN Barat",
                                "PTN wilayah barat Indonesia", "seleksi mandiri"]),
    "logo_bni": logo("Bank Negara Indonesia (BNI)", "simbol BNI 46 oranye bergaya 3D",
                     ["Bank Negara Indonesia", "BNI", "BNI 46", "Jakarta", "BUMN perbankan"]),
    "logo_bpjs": logo("BPJS", "logo BPJS (bentuk daun hijau dan lengkung biru) bergaya 3D",
                      ["BPJS", "Badan Penyelenggara Jaminan Sosial", "BPJS Kesehatan",
                       "BPJS Ketenagakerjaan", "Jakarta"]),
    "logo_bulog": logo("Perum Bulog", "logo Bulog (lengkung biru-kuning) bergaya 3D",
                       ["Perum Bulog", "Bulog", "Badan Urusan Logistik", "Jakarta", "BUMN pangan"]),
    "logo_freeport": logo("PT Freeport Indonesia", "logo Freeport (tulisan F:M dalam bingkai) berpalet brand",
                          ["PT Freeport Indonesia", "PTFI", "Freeport-McMoRan", "Timika", "Papua"]),
    "logo_mind_id": logo("MIND ID", "logo MIND ID (lingkaran merah terbuka dengan titik)",
                         ["MIND ID", "Mining Industry Indonesia", "holding BUMN tambang", "Jakarta"]),
    "logo_pln": logo("PT PLN (Persero)", "logo PLN (petir merah dan gelombang biru di kotak kuning)",
                     ["PT PLN (Persero)", "PLN", "Perusahaan Listrik Negara", "Jakarta", "BUMN energi"]),
    "logo_pertamina": logo("PT Pertamina (Persero)", "logo Pertamina (tiga jajaran genjang) bergaya 3D",
                           ["PT Pertamina (Persero)", "Pertamina", "Jakarta", "BUMN energi", "migas"]),
    "logo_pt_garam": logo("PT Garam (Persero)", "logo PT Garam member of ID FOOD",
                          ["PT Garam (Persero)", "PT Garam", "ID FOOD", "Surabaya", "BUMN pangan"]),
    "logo_jasa_raharja": logo("PT Jasa Raharja", "logo Jasa Raharja (lingkaran biru bergelombang)",
                              ["PT Jasa Raharja", "Jasa Raharja", "JR", "Jakarta", "asuransi BUMN"]),
    "logo_kai": logo("PT Kereta Api Indonesia (Persero)", "logo KAI (tulisan KAI biru-oranye) bergaya 3D",
                     ["PT Kereta Api Indonesia (Persero)", "KAI", "Kereta Api Indonesia", "Bandung",
                      "BUMN transportasi"]),
    "logo_telkom_indonesia": logo("PT Telkom Indonesia (Persero) Tbk",
                                  "logo Telkom Indonesia (tangan dan lingkaran) digambar ulang berpalet brand",
                                  ["PT Telkom Indonesia", "Telkom", "Telkom Indonesia", "Bandung",
                                   "BUMN telekomunikasi"]),
    "logo_ipdn": logo("Institut Pemerintahan Dalam Negeri", "logo IPDN (Garuda dalam lingkaran merah-putih)",
                      ["Institut Pemerintahan Dalam Negeri", "IPDN", "Jatinangor", "Sumedang",
                       "sekolah kedinasan", "Kemendagri"]),
    "logo_poltekim": logo("Politeknik Imigrasi", "logo Politeknik Imigrasi (perisai biru dengan gedung dan buku)",
                          ["Politeknik Imigrasi", "Poltekim", "Depok", "sekolah kedinasan", "imigrasi"]),
    "logo_pkn_stan": logo("Politeknik Keuangan Negara STAN", "logo PKN STAN (sayap emas dalam lingkaran biru)",
                          ["Politeknik Keuangan Negara STAN", "PKN STAN", "STAN", "Tangerang Selatan",
                           "Bintaro", "sekolah kedinasan"]),
    "logo_stin": logo("Sekolah Tinggi Intelijen Negara", "logo STIN (Garuda dalam lingkaran merah-kuning)",
                      ["Sekolah Tinggi Intelijen Negara", "STIN", "Bogor", "Sentul", "sekolah kedinasan",
                       "BIN"]),
    "logo_stis": logo("Politeknik Statistika STIS", "logo Politeknik Statistika STIS (lingkaran biru)",
                      ["Politeknik Statistika STIS", "STIS", "Jakarta", "sekolah kedinasan", "BPS"]),
}


# Judgment calls / uncertain groupings reported in SUMMARY.md (Indonesian).
# 'yakin' = seberapa yakin pengelompokannya (tinggi / sedang / rendah).
KEPUTUSAN = [
    {"judul": "Kimia Farma bukan logo resmi",
     "yakin": "sedang",
     "keputusan": "Digambar sebagai dua tablet obat dengan palet JadiBUMN, jadi dicatat sebagai glyph "
                  "`obat_tablet` (boleh diwarnai ulang), bukan `logo_kimia_farma`. Ubah ke tipe logo bila tim "
                  "menganggapnya representasi resmi perusahaan.",
     "files": ["JadiBUMN/kimia farma-icon.png"]},
    {"judul": "Ikon PLN ada dua jenis",
     "yakin": "tinggi",
     "keputusan": "PLN-Icon2 = logo resmi PLN (`logo_pln`). PLN-Icon = rambu segitiga petir, gambar yang sama "
                  "dengan glyph PPG teknik elektronika, jadi masuk `tanda_listrik` (glyph, boleh diwarnai ulang).",
     "files": ["JadiBUMN/PLN-Icon.png", "JadiBUMN/PLN-Icon2.png", "JadiPPG/Icon_Studi teknik elektronika.png"]},
    {"judul": "Nama file logo tidak cocok dengan gambarnya",
     "yakin": "sedang",
     "keputusan": "Icon-USM berisi logo UNS (Universitas Sebelas Maret), jadi `logo_uns`. Icon-USU berisi lambang "
                  "Kota Surabaya (Tugu Pahlawan, ikan sura dan buaya), bukan logo USU, jadi `logo_surabaya`. "
                  "Perlu dicek ke tim konten apakah file salah unggah.",
     "files": ["Cerebrum/Icon-USM.png", "Cerebrum/Icon-USU.png"]},
    {"judul": "Satu logo, dua file",
     "yakin": "tinggi",
     "keputusan": "Untitled-2 = logo Trisakti versi datar tanpa bayangan 3D, digabung ke `logo_trisakti` sebagai "
                  "varian. Mind-icon dan mind-id-logo-... adalah gambar yang sama, digabung ke `logo_mind_id`.",
     "files": ["Cerebrum/Icon-Trisakti.png", "Cerebrum/Untitled-2.png", "JadiBUMN/Mind-icon.png",
               "JadiBUMN/mind-id-logo-e1650472609768.png"]},
    {"judul": "Isi berbeda di bingkai yang sama dipisah jadi glyph sendiri",
     "yakin": "sedang",
     "keputusan": "Mengikuti aturan ubin 2x2: bila simbol atau teks di dalamnya membawa makna, glyph dipisah. "
                  "Puzzle polos (`puzzle`) dipisah dari puzzle bersimbol petir dan steker (`puzzle_listrik`) serta "
                  "minus dan kali (`puzzle_matematika`). Panel `abstraksi_ruang` dipisah dari versi bertulisan "
                  "D3-S2 (`rbb_d3_s2`) dan SMA (`rbb_sma`). Perisai berkubus (`perisai`) dipisah dari perisai "
                  "bergembok (`perisai_gembok`). Bisa digabung sebagai varian jika tim lebih suka.",
     "files": ["JadiBUMN/TKP PLN-Icon.png", "JadiOJK/icon_Kemampuan umum numerik.png",
               "JadiSekdin/icon_Materi matematika.png", "JadiBUMN/RBB-Icon.png", "JadiBUMN/RBB-SMA-Icon.png",
               "JadiPPPK/icon_Keamanan dan keselamatan.png"]},
    {"judul": "Balon percakapan: empat glyph berbeda",
     "yakin": "tinggi",
     "keputusan": "Dua balon berisi titik = `tips` (seed). Dua balon bertuliskan EN = `bahasa_inggris`, bertuliskan "
                  "INA = `bahasa_indonesia`. Satu balon besar dengan gelombang sinyal = `verbal`.",
     "files": ["Cerebrum/Icon-Tips.png", "Cerebrum/Icon-Eng.png", "Cerebrum/Icon-Ina.png", "JadiBUMN/Verbal.png"]},
    {"judul": "Penamaan `verbal` vs `soal_cerita`",
     "yakin": "sedang",
     "keputusan": "Ubin 'abc 5 cba ...' paling sering bernama 'Soal cerita' (3 brand), jadi id-nya `soal_cerita`. "
                  "Id `verbal` dipakai untuk balon bicara bergelombang, yang di keempat brand bernama 'Verbal'.",
     "files": ["JadiPPPK/icon_Soal cerita.png", "JadiSekdin/icon_ Soal cerita.png",
               "JadiOJK/icon_Numerik soal cerita.png", "JadiBUMN/Verbal.png", "JadiPPPK/icon_Verbal.png",
               "JadiSekdin/icon_Verbal.png", "JadiOJK/icon_Kemampuan umum verbal.png"]},
    {"judul": "Toga wanita dan pria dipisah",
     "yakin": "tinggi",
     "keputusan": "Dua gambar berbeda (rambut panjang vs pendek): `toga` (7 brand) dan `toga_pria` (2 brand).",
     "files": ["JadiPPG/Icon_Studi pendidikan luar biasa.png", "JadiPPPK/Icon_Tryout PPPK Sekolah Rakyat 2026.png"]},
    {"judul": "Lencana TOEFL tiga tingkat dipisah",
     "yakin": "tinggi",
     "keputusan": "Starter, Booster dan Ace digambar dengan jumlah chevron berbeda (1/2/3), jadi tiga glyph "
                  "`lencana_tingkat_1..3`, bukan varian warna.",
     "files": ["TOEFL Academy/icon_Starter test.png", "TOEFL Academy/icon_Booster test.png",
               "TOEFL Academy/icon_Ace test.png"]},
    {"judul": "Gambar yang digambar ulang tetap dianggap glyph yang sama (varian)",
     "yakin": "sedang",
     "keputusan": "Mengikuti seed (journey Cerebrum/BUMN dan tips ASN/Prajurit juga digambar sedikit berbeda): palu "
                  "hakim JadiBUMN yang digambar ulang tetap `palu_hakim`; kuantitatif Cerebrum dengan ubin (x) miring "
                  "tetap `kuantitatif`; ubin abc JadiBUMN dengan dua titik tetap `soal_cerita`; tanda silang "
                  "JadiPrajurit yang lebih lebar tetap `tutup`. Masing-masing diberi catatan `varian`.",
     "files": ["JadiBUMN/Hukum-Icon.png", "Cerebrum/Icon-PK.png", "JadiBUMN/Logic Reasoning-Icon.png",
               "JadiPrajurit/Menu-Close.png", "Cerebrum/Icon-Journey.png", "JadiBUMN/Journey-Icon.png",
               "JadiASN/Menu-Tips.png", "JadiPrajurit/Menu-Tips.png"]},
    {"judul": "Nama file menyesatkan (gambar lebih dipercaya daripada nama)",
     "yakin": "tinggi",
     "keputusan": "JadiPolisi/icon_Latsol.png bergambar Tryout (sesuai seed). Di JadiPPPK, 'icon_Tryout PPPK.png' "
                  "(tanpa spasi) = `puzzle`, sedangkan 'icon_Tryout PPPK .png' (dengan spasi) = `kertas_soal`. "
                  "Di JadiPPG nama tertukar: 'Icon_Studi bahasa indonesia' bergambar bendera Inggris "
                  "(`bendera_inggris`) dan 'Icon_Studi bahasa inggris' bergambar bendera Indonesia "
                  "(`bendera_indonesia`).",
     "files": ["JadiPolisi/icon_Latsol.png", "JadiPPPK/icon_Tryout PPPK.png", "JadiPPPK/icon_Tryout PPPK .png",
               "JadiPPG/Icon_Studi bahasa indonesia.png", "JadiPPG/Icon_Studi bahasa inggris.png"]},
    {"judul": "File tanpa nama bermakna, dikelompokkan murni dari gambar",
     "yakin": "tinggi",
     "keputusan": "JadiPPG/1.png sampai 14.png (lihat tabel pemetaan di bawah), JadiSekdin/icon.png (`palu_hakim`), "
                  "JadiSekdin/icon_.png (`globe`), JadiPrajurit/Artboard 14@4x.png (`layar_video`, satu-satunya "
                  "glyph tanpa alias) dan Cerebrum/Untitled-2.png (`logo_trisakti`).",
     "files": ["JadiSekdin/icon.png", "JadiSekdin/icon_.png", "JadiPrajurit/Artboard 14@4x.png",
               "Cerebrum/Untitled-2.png"]},
    {"judul": "Instance tambahan untuk glyph seed",
     "yakin": "tinggi",
     "keputusan": "Ditemukan gambar yang sama di luar seed: rapor (+3), grup (+2), kertas_soal (+1), materi (+2 versi "
                  "warna Cerebrum). Semua instance seed tetap di glyph seed-nya.",
     "files": ["JadiOJK/icon_Latihan soal.png", "JadiPCPM/icon_Latsol harian Assesment.png",
               "JadiPrajurit/icon_blanko .png", "JadiBUMN/Icon - Manajemen Bidang.png",
               "JadiSekdin/TKP - Jejaring kerja.png", "Cerebrum/Icon-Reading.png",
               "Cerebrum/Icon-Materi-Biru.png", "Cerebrum/Icon-Materi-Kuning.png"]},
    {"judul": "Label TIU/TKP/TWK 2024-2026 di JadiASN memakai glyph berbeda tiap tahun",
     "yakin": "tinggi",
     "keputusan": "Bukan kesalahan pengelompokan, hanya catatan: TIU 2024/2025/2026 = `kuantitatif`/`kalkulator`/"
                  "`numerik`; TKP 2024/2025/2026 = `bulu`/`topeng_drama`/`headset_cs`; TWK 2024/2025/2026 = "
                  "`abstraksi_ruang`/`gedung_pilar`/`garuda`.",
     "files": ["JadiASN/Icon_TIU 2024.png", "JadiASN/Icon_TIU 2025.png", "JadiASN/Icon_TIU 2026.png",
               "JadiASN/Icon_TKP 2024.png", "JadiASN/Icon_TKP 2025.png", "JadiASN/Icon_TKP 2026.png",
               "JadiASN/Icon_TWK 2024.png", "JadiASN/Icon_TWK 2025.png", "JadiASN/Icon_TWK 2026.png"]},
    {"judul": "Kategori ambigu (makna berbeda antar brand)",
     "yakin": "sedang",
     "keputusan": "Kategori dipilih dari makna dominan: `globe` (geografi/pengetahuan umum/TIU) masuk mapel; "
                  "`uang` (ekonomi/keuangan) masuk mapel; `roda_gigi` (teknik-op/checking test/psikometri/SSN) masuk "
                  "profesi_bidang; `bulu` (TKP/sosial budaya/seni rupa/TOEFL) masuk subtes; `kristal` (tryout tahap "
                  "1/STMKG) masuk lainnya; `monitor` (test/pengenalan/progres belajar) masuk menu; "
                  "`bendera_indonesia` (bahasa negara/TWK) masuk subtes; `rbb_d3_s2`/`rbb_sma`/`puzzle`/`perisai` "
                  "(jalur dan tahap seleksi) masuk subtes. Ilustrasi manusia bermakna umum (toga, CS, guru, "
                  "kerumunan) masuk orang, sedangkan yang mewakili jurusan atau mapel tertentu (koki, tukang las, "
                  "guru SD/PAUD, guru olahraga) mengikuti makna jurusan/mapelnya.",
     "files": []},
]
